name: testing-cli
on:
  workflow_dispatch:

  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'master'
jobs:
  run-cli-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository code
      - uses: actions/checkout@v3
      # Configure python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Setup the CRMint test environment
      - name: Setup CLI
        run: pip install ./cli[test]
      # Run the tests
      - name: Run the tests
        working-directory: cli
        run: pytest --cov=. --cov-report=xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
